version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node@10-stretch

    steps:
      - checkout

      - restore_cache:
          name: Restore cached Node modules
          keys:
            - node-modules-{{ checksum "yarn.lock" }}
            # Fallback to using the latest cache if no exact match is found.
            - node-modules-

      - run:
          name: Install Node modules
          command: yarn install --frozen-lockfile

      - save_cache:
          name: Cache Node modules
          key: node-modules-{{ checksum "yarn.lock" }}
          paths:
            - ./cache/node_modules

      - run:
          name: Check types
          command: yarn run check-types

      - run:
          name: Lint
          command: yarn run lint
