version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:10

    steps:
      - checkout

      - restore_cache:
          name: Restore cached Node modules
          keys:
            - node-modules-{{ checksum "yarn.lock" }}
            # Fallback to using the latest cache if no exact match is found.
            - node-modules-

      - run:
          name: Install Node modules
          command: yarn install --frozen-lockfile

      - save_cache:
          name: Cache Node modules
          key: node-modules-{{ checksum "yarn.lock" }}
          paths:
            - ./cache/node_modules

      - run:
          name: Check types
          command: yarn run check-types

      - run:
          name: Lint
          command: yarn run lint

      - run:
          name: Sign in to Expo
          # expo_password is defined as an environment variable in CircleCI.
          command: yarn expo login --username janaagaard75 --password $expo_password

      - run:
          name: Publish to Expo
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              yarn expo publish --quiet
            else
              yarn expo publish --quiet --release-channel "${CIRCLE_BRANCH}"
            fi
